---
- name: Symlink ZSHRC
  ansible.builtin.file:
    src: "{{ user_config }}/zsh/.zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    state: link
  when: 0 == 1

- name: Symlink configs
  become: true
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ user_profile }}/.config/zsh/profiles", dest: "{{ user_config }}/zsh/profiles" }
    - { src: "{{ user_profile }}/.config/nvim-profile", dest: "{{ user_config }}/nvim-profile" }

- name: Change to ZSH shell
  become: true
  ansible.builtin.shell: "usermod -s $(which zsh) {{ ansible_user_id }}"
