---
- name: Copy user templated files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.path | splitext | first }}"
  with_filetree: "templates/home"
  when: item.state == 'file'

- name: Change to ZSH shell
  become: true
  ansible.builtin.shell: "usermod -s $(which zsh) {{ ansible_user_id }}"
