---
- name: Copy system files
  become: true
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/{{ item.path | relpath('os/') }}"
  with_filetree: "files/os"
  when: item.state == 'file'

- name: Copy templated system files
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/{{ item.path | splitext | first | relpath('os/') }}"
  with_filetree: "templates/os"
  when: item.state == 'file'
